version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fap_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fap_traceability
      POSTGRES_USER: fap_user
      POSTGRES_PASSWORD: fap_password
    ports:
      - "5432:5432"
    volumes:
      - fap_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fap_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: fap_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: fap_minio
      MINIO_ROOT_PASSWORD: fap_minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - fap_minio_data:/data

volumes:
  fap_postgres_data:
  fap_minio_data:
